### ISSUE TITLE
JH71x0 needs documented

### ISSUE THREAD

**Issue by robertlipe** [starfive-tech/opensbi#1]
So it's not forgotten, JH7100 and JH7110 need documented in
https://github.com/starfive-tech/sft-riscv-opensbi/blob/starfive/docs/platform/platform.md
and probably a dedicated doc in
https://github.com/starfive-tech/sft-riscv-opensbi/tree/starfive/docs/platform

From: https://github.com/starfive-tech/sft-riscv-opensbi/issues/3

**Comment by pdp7** [comment]
I spoke to @tekkamanninja earlier today and he believes we should be able to use the generic platform.

@avpatel @lbmeng does that sound right to you, too?

**Comment by avpatel** [comment]
Generic platform is the right way to go. It saves maintenance efforts and allows us to use same firmware binaries on multiple boards.

Regards,
Anup

**Comment by lbmeng** [comment]
We should switch to upstream OpenSBI and use the generic platform firmware for BeagleV.

**Comment by pdp7** [comment]
@lbmeng that seems like a good suggestion so I have opened #4

**Comment by pdp7** [comment]
beaglev starlight is using generic platform so we will not need any board specific documentation opensbi
