### ISSUE TITLE
贵司不妨试试RustSBI？

### ISSUE THREAD

**Issue by luojia65** [starfive-tech/opensbi#7]
优点：
1. 产权代码不需要合并到上游
2. 和rust生态结合紧密，能吸引rust嵌入式用户，比如高效科研和教研团队、更多嵌入式公司
3. 国产化要求高的客户禁止使用opensbi

可以牵头开一个仓库，由开源社区来做细节，不一定要由贵司全部完成。

**Comment by tekkamanninja** [comment]
> 优点：
> 
> 1. 产权代码不需要合并到上游

starfive 还是比较关注开源解决方案的，upstream first

> 2. 和rust生态结合紧密，能吸引rust嵌入式用户，比如高效科研和教研团队、更多嵌入式公司

很好

> 3. 国产化要求高的客户禁止使用opensbi

请您具体叙述下禁止使用opensbi的缘由， 和RustSBI的优势

> 
> 可以牵头开一个仓库，由开源社区来做细节，不一定要由贵司全部完成。
如果您可以移植到qemu和beaglev, 我很愿意尝试

**Comment by luojia65** [comment]
我可去你的吧，还敢私信骚扰？你司就这素质？

**Comment by luojia65** [comment]
@tekkamanninja
1. 开源并不意味着合并到主分支！非技术因素很多，恕不列举！
2. 我觉得说这句话的意思是：我很敷衍，你们一点用都没有，我根本没有把你们的项目当回事。
3. 我就不想用你有什么办法
4. 你可能没有做够调研，https://github.com/rustsbi/rustsbi-qemu。只有原厂有beaglev板子！对我们甚至都不卖！很不公平！

**Comment by tekkamanninja** [comment]
> @tekkamanninja
> 
> 1. 开源并不意味着合并到主分支！非技术因素很多，恕不列举！
> 2. 我觉得说这句话的意思是：我很敷衍，你们一点用都没有，我根本没有把你们的项目当回事。
> 3. 我就不想用你有什么办法

无意冒犯，如您觉得冒犯到了您，请谅解。但绝无此意，初次看到此项目确实不太了解 ，个人知识水平有限，恕我无知。

> 4. 你可能没有做够调研，https://github.com/rustsbi/rustsbi-qemu 。只有原厂有beaglev板子！对我们甚至都不卖！很不公平！不过如果愿意开一个仓库，可以对照qemu的写法大家一起维护，只要仓库在starfive下就可以

这个仓库确实没看到，抱歉，我的疏忽。开仓问题请直接咨询赛昉的员工，比如（我只是开源社区开发者）。

请理解原厂此次（MPW）芯片数量有限（大概全球开发者才300片不到），作为早期Image社区开发参与者，我仅也就只有一块有点小瑕疵（reset功能没改版前）的测试板（最终给开发者的Beta版都比我手上的好，说实话看到他们带有大散热片的正式版本，我也很羡慕）用于内核开发和Image验证。而且板子不是“甚至都不卖”，而是根本没打算拿这批 *beta版本的* 开发板换钱，仅为社区开发和培养相关软件生态用。但是后期会有数量较大的beta版本出来，总数量可能上千片，您可以通过这个链接申请： https://starfive.mikecrm.com/2XzBQqh

但凡看到有新的想法，我个人都尽力帮忙测试和验证，只是还在忙其他开发事情，确实没有太多时间验证，您可以指导下看看我这里可以如何帮您验证测试。
